// vue/src/components/ToastContainer.vue
<template>
    <div class="erag-toast-container" :class="`erag-${state.position}`">
        <TransitionGroup name="erag-toast-list">
            <Toast
                v-for="toast in state.toasts"
                :id="toast.id"
                :key="toast.id"
                :type="toast.type"
                :title="toast.title"
                :message="toast.message"
                :duration="toast.duration"
                @close="remove"
            />
        </TransitionGroup>
    </div>
</template>

<script setup lang="ts">
import { useToast } from '../composables/useToast';
import Toast from './Toast.vue';

const { state, remove } = useToast();
</script>

<style scoped>
.erag-toast-container {
    position: fixed;
    z-index: 9999;
    display: flex;
    flex-direction: column;
}

/* Positions with Prefix */
.erag-toast-container.erag-top-left {
    top: 20px;
    left: 20px;
}
.erag-toast-container.erag-top-center {
    top: 20px;
    left: 50%;
    transform: translateX(-50%);
}
.erag-toast-container.erag-top-right {
    top: 20px;
    right: 20px;
}

.erag-toast-container.erag-bottom-left {
    bottom: 20px;
    left: 20px;
}
.erag-toast-container.erag-bottom-center {
    bottom: 20px;
    left: 50%;
    transform: translateX(-50%);
}
.erag-toast-container.erag-bottom-right {
    bottom: 20px;
    right: 20px;
}
</style>

// react/src/components/ToastContainer.tsx
import Toast from './Toast';
import { useToast } from '../hooks/useToast';

export default function ToastContainer() {
    const { state, remove } = useToast();

    return (
        <div className={`erag-toast-container erag-${state.position}`}>
            {state.toasts.map((toast) => (
                <Toast
                    key={toast.id}
                    id={toast.id}
                    type={toast.type}
                    title={toast.title}
                    message={toast.message}
                    duration={toast.duration}
                    onClose={remove}
                />
            ))}
        </div>
    );
}
